### ISSUE TITLE
When not using Anchore, disable Anchore UI items as they will throw an error

### ISSUE THREAD

**Issue by hugodopradofernandes** [klustair/klustair-frontend#11]
When not using Anchore, disable Anchore UI items as they will throw an error.
There is a plan to rebuild the UI to match only items from **trivy**?

**Comment by mms-gianni** [comment]
Yes, you are right. Anchore is on the way out. I was not sure if I want to support Trivy and Anchore, but it seem so be to much work. And Anchore has a much bigger footprint, while Trivy has more detailed results. 

Anchore results are basically just a list of CVE's with links, which have to be checked separately. 

My heart is bleeding a bit, since i've put quite a bit of work into it.

**Comment by mms-gianni** [comment]
What's your preference? 

- Keep Anchore as alternative
- Keep Anchore in parallel to Trivy as a 2nd class citizen 
- Remove Anchore completely and go full with Trivy

In my Usecase I'm only using Trivy. 

The plus of Anchore are: 
+ Policy checks on Dockerfiles (needs a lot of maintenance)
+ Displayable Dockerfile (Looks nice, but not a big benefit)
+ More details on the Image, for example number of layers (Nice to know, but not a big benefit)
+ Asynchronous checks (But checks take a bit longer)
+ Possibility of submitting images, which are not running in your cluster
+ Automatic rechecks when a image is rebuild/published

The Downsites of Anchore are:
- Requires manually removing the image, when tags change or images are not longer used
- Big footprint
- More complexity (to setup/maintain and to work with)
- Missing detail information on vulnerabilities (Filed a feature request in Anchore for that since this is crucial https://github.com/anchore/anchore-engine/issues/670 )

**Comment by hugodopradofernandes** [comment]
I think the best is supporting both tools, as you already did the work to support both, but require some work to have the UI with items enabled only for tools the user is using.
