### ISSUE TITLE
UI should display the current version and some other info

### ISSUE THREAD

**Issue by hugodopradofernandes** [klustair/klustair-frontend#15]
UI should display the current version and some other info:
- Version
- Home page (this github repo)
- Documentation: This git hub repo or trivy and kubeaudit pages

**Comment by mms-gianni** [comment]
This is a very good idea. 

- Version is no problem. I just hope, I will never forget to update the version everywhere. 😄  
- Since there is klustair organisation Repo with all relevant repositories, I will https://github.com/klustair 
- Since there is no adequate documentation will wait to add a link. But I will prepare the place in the footer.
